### ISSUE TITLE
Compute FID

### ISSUE THREAD

**Issue by matt-bendel** [utcsilab/csgm-mri-langevin#3]
I noticed in the config file there is a langevin_config called fast_fid. Is there code implemented in this repository to compute FID? If I am missing something obvious, I apologize. Also, do you know approximately how long it takes to generate those 1000 samples for a given set of measurements?

**Comment by mariusarvinte** [comment]
Hi,

We never used or reported FID in the paper / experiments, the config is leftover from the original NCSNv2 repo. That being said, it seems they do have FID here: https://github.com/ermongroup/ncsnv2/blob/master/evaluation/fid_score.py, but like I said we never actually used or ran it, since it's not common for MRI.

In terms of running time, I just verified and it takes approximately 14.5 minutes for a single knee image of size 640 x 320 to be reconstructed on an NVIDIA RTX 3090. The VRAM used is only ~1.5 GB, so batching will definitely help there.

**Comment by matt-bendel** [comment]
Great! Thank you for your quick response!
